FROM yaamai/codimd:latest-oidc
LABEL maintainer Yuki Takei <yuki@weseek.co.jp>

# copy script to apply GROWI agent
USER root
COPY deployments/apply-growi-agent.sh /codimd/apply-growi-agent.sh
RUN chmod +x /codimd/apply-growi-agent.sh
# run the script
RUN /codimd/apply-growi-agent.sh

# overwrite HackMD config file
RUN rm -f /files/config.json && rm -f /codimd/config.json
COPY deployments/config.json /files/
RUN mkdir -p /codimd/config && ln -s /files/config.json /codimd/config/config.json

# create sqlite data dir
RUN mkdir /files/sqlite && chown codimd /files/sqlite
RUN ln -s /files/sqlite /codimd/sqlite

COPY deployments/docker-entrypoint.sh /codimd/docker-entrypoint.sh
USER codimd
